Repository AY2425S2-CS2113-F14-3/tp, pull requests merged in 2025-04, with the labels that each got.

#125 Dev/91 add day to transportation
  docs/UserGuide.md
  src/main/java/voyatrip/Transportation.java
  src/main/java/voyatrip/Trip.java
  src/main/java/voyatrip/VoyaTrip.java
  src/main/java/voyatrip/command/types/TransportationCommand.java
  src/test/java/voyatrip/TripTest.java
  src/test/java/voyatrip/command/ParserTest.java
Labels: priority.High

#132 Dev/95 add list transportation
  docs/UserGuide.md
  src/main/java/voyatrip/Trip.java
  src/main/java/voyatrip/VoyaTrip.java
  src/main/java/voyatrip/command/exceptions/TransportationException.java
  src/main/java/voyatrip/command/types/TransportationCommand.java
  src/main/java/voyatrip/ui/Message.java
  src/main/java/voyatrip/ui/Ui.java
Labels: priority.High

#139 Dev/133 modification of transportation
  docs/UserGuide.md
  src/main/java/voyatrip/Transportation.java
  src/main/java/voyatrip/Trip.java
  src/main/java/voyatrip/VoyaTrip.java
  src/main/java/voyatrip/command/exceptions/InvalidDayDuration.java
  src/main/java/voyatrip/command/types/TransportationCommand.java
  src/main/java/voyatrip/ui/Message.java
  src/main/java/voyatrip/ui/Ui.java
Labels: priority.Medium

#211 Fix/160 more exception messages
  src/main/java/voyatrip/Day.java
  src/main/java/voyatrip/Trip.java
  src/main/java/voyatrip/VoyaTrip.java
  src/main/java/voyatrip/command/Parser.java
  src/main/java/voyatrip/command/exceptions/AccommodationNotFound.java
  src/main/java/voyatrip/command/exceptions/ActivityNotFound.java
  src/main/java/voyatrip/command/exceptions/DuplicatedName.java
  src/main/java/voyatrip/command/exceptions/InvalidBudget.java
  src/main/java/voyatrip/command/exceptions/InvalidDate.java
  src/main/java/voyatrip/command/exceptions/InvalidDateFormat.java
  src/main/java/voyatrip/command/exceptions/InvalidDay.java
  src/main/java/voyatrip/command/exceptions/InvalidIndex.java
  src/main/java/voyatrip/command/exceptions/InvalidName.java
  src/main/java/voyatrip/command/exceptions/InvalidNumberFormat.java
  src/main/java/voyatrip/command/exceptions/TransportationNotFound.java
  src/main/java/voyatrip/command/types/AccommodationCommand.java
  src/main/java/voyatrip/command/types/Command.java
  src/main/java/voyatrip/command/types/ItineraryCommand.java
  src/main/java/voyatrip/command/types/TransportationCommand.java
  src/main/java/voyatrip/command/types/TripsCommand.java
  src/main/java/voyatrip/ui/Message.java
  src/main/java/voyatrip/ui/Ui.java
  src/test/java/voyatrip/DayTest.java
Labels: priority.High, severity.High

#239 Fix/238 Add restriction for deleting trip
  src/main/java/voyatrip/logic/executor/Executor.java
Labels: priority.High

#241 Dev/225 update user developper guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/uml/uml_v1.puml
Labels: priority.High

#250 Fix invalid portfolio path
  docs/AboutUs.md
Labels: priority.High
